### PR TITLE
chore: set a distinct client version string

### PR DESCRIPTION
**Pull request by m-schmoock**
In order to find out about consensus we should change the client version string properly.
This way we can track usage of this branch i.e here: https://bitnodes.21.co/nodes

### CODE REVIEW

**Comment by kleetus** [comment]
Thanks for sending this merge request. I see your point, but I would ask the following to spur conversation: 

The client name of the software really is "Satoshi". Almost of the code is Satoshi's, but with some patching. Admittedly, the whole concept of having a "version" protocol message is a bit quaint. At this point, the answer to a version message ought to be "whatever you want it to be man". All things being equal, just saying this is Satoshi's client is least likely to raise an eyebrow or otherwise cause a holy war. I am all for using "uacomment=bitcore" in the config or on the command line for the daemon. Do you have a different take on this issue considering the above?

**Comment by martindale** [comment]
The client version string should be considered meaningless, much like the User Agent string in HTTP headers.  It can be (and very often is) quite misleading.

**Comment by m-schmoock** [comment]
Its correct, however, as there is no established voting support within the software, the community tends to interpret node usage a weak indicator for 'users vote' (see https://coin.dance/nodes or http://xtnodes.com )

**Comment by kleetus** [comment]
my latest thoughts on this subject are that: 
- the response to the "version" P2P message ought to be a biit mask ala bip009, except instead of block version, node P2P version 

https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki

this would allow nodes to report its capabilities, separate from brands like classic/core/satoshi/unlimited/bitcore. Example, if the 5th MSB is set, this might mean that this node supports adaptive block size. If the 4th bit is set, then this node might also support a 2MB hard fork. 
- If the version message is truly meaningless, then we should remove it altogether.

**Comment by m-schmoock** [comment]
Thats sounds great. I was thinking about the same issue when announcing/voting several BIPs like 109 and BitPay simultaneously. I guess you saw my additional merge request to the BIP...

Because it totally valid to vote several BIPs at once without knowing which will be activated first. There should be a configuration option for consensus voting/announcement.

**Pull request closed without merging**
