### PR TITLE
Update to 0.13.0

### PR DESCRIPTION
**Pull request by braydonf**
Rebased bitcore patches from 0.12.1 to 0.13:
- https://github.com/bitpay/bitcoin/tree/0.12.1-bitcore (full history)
- https://github.com/braydonf/bitcoin/commits/0.12.1-bitcore-squashed (squashed history for rebasing)

Includes all changes except the wallet-utility at https://github.com/braydonf/bitcoin/commit/352ec3de19b3940263bca6b96a9be44e4427b95e which can possibly be included or added with another pull request.

Closes https://github.com/bitpay/bitcoin/issues/32

### CODE REVIEW

**Comment by moeadham** [comment]
Is this stable? Has anyone tried running bitcore-node against this version?

**Comment by braydonf** [comment]
I did quite awhile ago, bitcore-node needs segwit https://github.com/bitpay/bitcore-lib/pull/50 version of bitcore-lib to handle serialization of transactions on testnet.

**Comment by moeadham** [comment]
Thanks @braydonf Braydonf. I'm working on a fork of bitcore/insight-api that updates bitcoin-core more frequently, ill make sure to pull in those changes.

Nice work btw.

**Comment by STRML** [comment]
@moeadham Have you had any progress with that? With UASF on the way we'll need to make a change soon.

**Pull request merged**
